### ISSUE TITLE
IE11 failure

### ISSUE THREAD

**Issue by bryankaplan** [zachleat/fontfaceonload#14]
One of my users is on Windows 8.1 using IE11. FontFaceOnload in her browser consistently times out, triggering FontFaceOnload's error() callback.

I haven't been able to reproduce this on my own, but it's reliably happening on her particular machine. Chrome on that machine works for her though.

**Comment by zachleat** [comment]
I hope this resolution doesn’t discourage you from opening tickets like this! It’s important to have things like this in the issue database in case others have the same problem. So thank you!
