### ISSUE TITLE
Problem with on-site files with Google Chrome

### ISSUE THREAD

**Issue by MarvinLeRouge** [zachleat/fontfaceonload#15]
When using [files located inside current website, doesn't seem to work](http://goo.gl/ZqXjrK) (fontface with src files in the same website causes error message). Nevertheless, the font file is loaded (visible in network inspector).
But ok with [out-site links](http://goo.gl/lfVF8P) (link tag with reference to google font).

Am i doing something wrong ? Thanks

**Comment by MarvinLeRouge** [comment]
After some research, it seems 
a) specific to Google Chrome
b) unspecific to file type (woff and woff2 have the same problem)
c) not coming from a badly formated file on-site : i uploaded the same file google font sent me, and the problem stands.

**Comment by zachleat** [comment]
You’re correct! There was an error in the font-weights comparison. It was only working with numeric weights in the font-face blocks. I’ll push a new version with a fix.

**Comment by MarvinLeRouge** [comment]
Thanks a lot !
