### ISSUE TITLE
Loading fails on Firefox if no glyphs option is passed

### ISSUE THREAD

**Issue by ayamflow** [zachleat/fontfaceonload#21]
Happens on latest Firefox and Developer Edition too (Mac OS X) - no issues on Chrome/Safari.
I also have these errors in the CSS:

```
downloadable font: DSIG: table overruns end of file (<file.otf>)
downloadable font: rejected by sanitizer (<file.otf>)
```

Loading of a custom font was throwing an error, turns out it's from [this line](https://github.com/zachleat/fontfaceonload/blob/5f79046a20580bc9d7d88875734d3a8492430a48/src/fontfaceonload.js#L168).

I just passed the glyphs from the example, `glyphs: "\uE600\uE601\uE602\uE605"` and it works.

Seems like unexpected behavior but maybe there's a reason behind this?

**Comment by Aetherpoint** [comment]
I tried passing stuff like '\u000' outside of of the private use area and was still getting that same bug on Firefox Developer Edition.

¯\_(ツ)_/¯

**Comment by zachleat** [comment]
I believe this is fixed now in Firefox, just tested it locally. Please reopen if you’re still having problems!
