### ISSUE TITLE
Problems with load fonts in Firefox

### ISSUE THREAD

**Issue by nicofonseca** [zachleat/fontfaceonload#24]
Hi Zach, Thank you for this great plugin.

I've been having an issue with Firefox and it's that I can't manage to load any fonts. I thought it was something on my end but I'm having the same problem using your examples. Is there any way to do this?

Thanks in advance!

**Comment by zachleat** [comment]
Yes I just ran into this on my stuff as well. I have a fix, I'll post it shortly.

**Comment by zachleat** [comment]
Look for this in v0.1.7

**Comment by nicofonseca** [comment]
Works perfectly!  Thanks a lot Zach! :)
